<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IRW_MP_PROPERTIES
[<!ELEMENT IRW_MP_PROPERTIES (FORMAT)*>
<!ELEMENT FORMAT (PROP)*>
<!ATTLIST FORMAT name CDATA #REQUIRED>
<!ELEMENT PROP (#PCDATA)>
<!ATTLIST PROP name CDATA #REQUIRED>
<!ATTLIST PROP type CDATA #REQUIRED>
<!ATTLIST PROP token CDATA #IMPLIED>
]>
<IRW_MP_PROPERTIES>
    <FORMAT name="JPEG">
        <PROP name="Type" type="string">IMAGE</PROP>
        <PROP name="Format" type="string">JPEG</PROP>
        <PROP name="Width" type="unsigned long" token="doc_token_width_tn">100</PROP>
        <PROP name="Height" type="unsigned long" token="doc_token_height_tn">100</PROP>
        <PROP name="Compression" type="string">JPEG</PROP>
        <PROP name="Colormode" type="string">RGB</PROP>
        <PROP name="Jpeg Quality" type="unsigned long">300</PROP>
    </FORMAT>
</IRW_MP_PROPERTIES>